### ISSUE TITLE
frontend: no products found page shows when loading product list 

### ISSUE THREAD

**Issue by ashdaily** [ashdaily/turbocommerce#109]
- make the page appear only when necessary  
- redesign the `no products found` page again 
- For inspiration please check & ignore the animation https://static.wixstatic.com/media/72c0b2_90e54ce9926e41daac87a20b1ce9c908~mv2.gif

**Comment by charanjeet5ingh** [comment]
![Screenshot 2021-05-28 at 10 33 32 PM](https://user-images.githubusercontent.com/17945473/120018432-c7d59e80-c004-11eb-9229-8b4945241e2e.png)

@ashdaily please review this design.

**Comment by ashdaily** [comment]
Looks great @charanjeet5ingh
